### ISSUE TITLE
** (File.Error) could not remove files and directories recursively from.. not owner - mix ecto.create and mix phx.server

### ISSUE THREAD

**Issue by Elizaira** [Elizaira/phoenix#1]
**Environment**

- Elixir version: 1.8.2
- Node Version 12.4.0
- Chocolatey
- Database (PostgreSQL) version: 11.4
- Operating System: Windows 10
- Phoenix ecto version 3.2
- Cowboy 2.0

After I make a Phoenix project named "project" `mix phx.new project`, `cd project` I try to create a database `mix ecto.create` then I got an error:

`** (File.Error) could not remove files and directories recursively from "c:/Users/Phoenix/project/_build/dev/lib/ranch": not owner
    (elixir) lib/file.ex:1252: File.rm_rf!/1
    (mix) lib/mix/tasks/deps.compile.ex:66: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.compile.ex:64: Mix.Tasks.Deps.Compile.compile/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:89: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/loadpaths.ex:35: Mix.Tasks.Loadpaths.run/1` 

Can anyone help me? I'm new to Phoenix and I cannot install the Phoenix framework because of this error. Thank you.

**Comment by Elizaira** [comment]
After all of the solutions, I've tried to run the Phoenix Framework. Just re-install all the applications installed like Elixir, Erlang, PostgreSQL, and others. then follow the instructions here: https://hexdocs.pm/phoenix/up_and_running.html
